spring:
  datasource:
    url: jdbc:mysql:///myblog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
mybatis:
  type-aliases-package: com.lmt.domain
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: warn
    com.lmt: info
  file:
    name: log/blog-pro.log